[build]
  command = "npm run build"
  publish = "build/"
  functions = "functions/"

[[headers]]
  for = "/*.woff"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Type = "application/font-woff"